# Generated by Django 4.2.2 on 2023-06-09 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cylinder_count', models.PositiveSmallIntegerField()),
                ('passenger_count', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=250)),
                ('cylinder_volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('owner_name', models.CharField(max_length=250)),
            ],
            options={
                'permissions': [('search_car', 'Can search between cars')],
            },
        ),
    ]
